import type { Item } from "./types";

const colors = [
  "oklch(0.75 0.12 30)",
  "oklch(0.7 0.14 150)",
  "oklch(0.72 0.13 250)",
  "oklch(0.78 0.13 80)",
  "oklch(0.72 0.14 340)",
  "oklch(0.75 0.13 200)",
  "oklch(0.74 0.13 50)",
  "oklch(0.72 0.13 290)",
];

const c = (i: number) => colors[i % colors.length];

export const SEED_ITEMS: Item[] = [
  {
    id: "pressure-washer",
    name: "Pressure washer",
    emoji: "🧼",
    category: "outdoor",
    owner: { name: "Maria", avatarColor: c(0) },
    distanceMi: 0.05,
    doorsAway: "2 doors down",
    availability: "Free this weekend",
    availabilityTags: ["weekend", "saturday", "sunday"],
    estimatedValue: 320,
    synonyms: ["pressure washer", "power washer", "powerwasher", "karcher"],
  },
  {
    id: "cordless-drill",
    name: "Cordless drill",
    emoji: "🔩",
    category: "tools",
    owner: { name: "James", avatarColor: c(1) },
    distanceMi: 0.1,
    doorsAway: "4 doors down",
    availability: "Any weekday evening",
    availabilityTags: ["weekday", "evening", "tonight", "today", "tomorrow"],
    estimatedValue: 140,
    synonyms: ["drill", "cordless drill", "impact driver", "power drill"],
  },
  {
    id: "extension-ladder",
    name: "Extension ladder",
    emoji: "🪜",
    category: "outdoor",
    owner: { name: "Priya", avatarColor: c(2) },
    distanceMi: 0.3,
    doorsAway: "Around the corner",
    availability: "Free anytime",
    availabilityTags: ["weekend", "weekday", "today", "tomorrow"],
    estimatedValue: 220,
    synonyms: ["ladder", "extension ladder", "step ladder", "tall ladder"],
  },
  {
    id: "stand-mixer",
    name: "Stand mixer",
    emoji: "🥣",
    category: "kitchen",
    owner: { name: "Tom", avatarColor: c(3) },
    distanceMi: 0.2,
    doorsAway: "Across the street",
    availability: "Free this week",
    availabilityTags: ["weekday", "today", "tomorrow"],
    estimatedValue: 380,
    synonyms: ["stand mixer", "mixer", "kitchenaid clone"],
  },
  {
    id: "camping-tent",
    name: "4-person camping tent",
    emoji: "⛺",
    category: "outdoor",
    owner: { name: "Sofia", avatarColor: c(4) },
    distanceMi: 0.4,
    doorsAway: "Top of the block",
    availability: "Free next weekend",
    availabilityTags: ["weekend", "saturday", "sunday", "next week"],
    estimatedValue: 260,
    synonyms: ["tent", "camping tent", "4 person tent"],
  },
  {
    id: "hedge-trimmer",
    name: "Hedge trimmer",
    emoji: "🌿",
    category: "outdoor",
    owner: { name: "Dev", avatarColor: c(5) },
    distanceMi: 0.15,
    doorsAway: "3 doors down",
    availability: "Free Saturday",
    availabilityTags: ["weekend", "saturday"],
    estimatedValue: 180,
    synonyms: ["hedge trimmer", "trimmer", "hedge cutter"],
  },
  {
    id: "carpet-cleaner",
    name: "Carpet cleaner",
    emoji: "🧽",
    category: "home",
    owner: { name: "Aisha", avatarColor: c(6) },
    distanceMi: 0.25,
    doorsAway: "Two blocks over",
    availability: "Free this weekend",
    availabilityTags: ["weekend", "saturday", "sunday"],
    estimatedValue: 290,
    synonyms: ["carpet cleaner", "rug shampooer", "rug cleaner", "bissell"],
  },
  {
    id: "projector",
    name: "1080p projector",
    emoji: "📽️",
    category: "tech",
    owner: { name: "Leo", avatarColor: c(7) },
    distanceMi: 0.12,
    doorsAway: "Next door but one",
    availability: "Free Friday night",
    availabilityTags: ["weekend", "friday", "tonight"],
    estimatedValue: 240,
    synonyms: ["projector", "beamer", "movie projector"],
  },
  {
    id: "folding-tables",
    name: "Folding tables (×2)",
    emoji: "🪑",
    category: "home",
    owner: { name: "Hana", avatarColor: c(0) },
    distanceMi: 0.18,
    doorsAway: "5 doors down",
    availability: "Free anytime",
    availabilityTags: ["weekend", "weekday", "today"],
    estimatedValue: 120,
    synonyms: ["folding tables", "tables", "party tables", "trestle table"],
  },
  {
    id: "kids-bike",
    name: "Kids' bike (16\")",
    emoji: "🚲",
    category: "outdoor",
    owner: { name: "Marco", avatarColor: c(1) },
    distanceMi: 0.22,
    doorsAway: "Behind the playground",
    availability: "Free this week",
    availabilityTags: ["weekday", "weekend", "today", "tomorrow"],
    estimatedValue: 160,
    synonyms: ["kids bike", "bike", "bicycle", "child bike"],
  },
  {
    id: "sewing-machine",
    name: "Sewing machine",
    emoji: "🧵",
    category: "craft",
    owner: { name: "Yuki", avatarColor: c(2) },
    distanceMi: 0.08,
    doorsAway: "3 doors down",
    availability: "Free weekday evenings",
    availabilityTags: ["weekday", "evening", "tonight"],
    estimatedValue: 210,
    synonyms: ["sewing machine", "sewing", "singer", "brother machine"],
  },
  {
    id: "jigsaw",
    name: "Jigsaw",
    emoji: "🪚",
    category: "tools",
    owner: { name: "Owen", avatarColor: c(3) },
    distanceMi: 0.16,
    doorsAway: "End of the block",
    availability: "Free Saturday",
    availabilityTags: ["weekend", "saturday"],
    estimatedValue: 110,
    synonyms: ["jigsaw", "saw", "power saw"],
  },
  {
    id: "wheelbarrow",
    name: "Wheelbarrow",
    emoji: "🛞",
    category: "outdoor",
    owner: { name: "Beth", avatarColor: c(4) },
    distanceMi: 0.09,
    doorsAway: "Two doors over",
    availability: "Free anytime",
    availabilityTags: ["weekday", "weekend", "today"],
    estimatedValue: 130,
    synonyms: ["wheelbarrow", "garden cart", "cart"],
  },
  {
    id: "kitchenaid",
    name: "KitchenAid stand mixer",
    emoji: "🎂",
    category: "kitchen",
    owner: { name: "Nora", avatarColor: c(5) },
    distanceMi: 0.14,
    doorsAway: "4 doors down",
    availability: "Free this weekend",
    availabilityTags: ["weekend", "saturday", "sunday"],
    estimatedValue: 450,
    synonyms: ["kitchenaid", "kitchen aid", "stand mixer", "mixer"],
  },
];
